sudo: required

services:
  - docker
  
before_install:
  - docker build -t sl10/docker-react .
#  - docker build -t sl10/docker-react -f Dockerfile.dev .
  
#script:
#  - docker run sl10/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-012136132533"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Key"